import "./globals.css";
import type {Metadata} from "next";
import {GeistSans, GeistMono} from "geist/font";
import styles from "./layout.module.css";

export const metadata: Metadata = {
  title: "My Vercelian Profile",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang="en" className={`${GeistSans.variable} ${GeistMono.variable}`}>
      <body className={GeistSans.className}>
        <main className={styles.main}>{children}</main>
      </body>
    </html>
  );
}
